name = "PrimeNumberTheoremAnd"
version = "0.1.0"
defaultTargets = ["PrimeNumberTheoremAnd"]

[[require]]
name = "Dress"
git = "https://github.com/e-vergo/Dress"
rev = "main"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
